OrdererOrgs:
  - Name: Orderer
    Domain: cpu-network
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: ngp
    Domain: ngp-cpu-network
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 0
